apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: demo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
