apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - port: 80        # Service port
      targetPort: 80  # Container port
      nodePort: 30080 # Host port
